#ifndef __GUESSMT_H
#define __GUESSMT_H

#define MAX_VALUE       1000
#define MSG_BUF_SIZE    100

typedef  struct gmn_t {
    int value;                      /* value generated by the child */
    int guess;                      /* number guessed by the parent */
    int result;                     /* -1, 0 or 1 depending on the guess*/
    int status;                     /* Predicate to check if a guess is made */
    char message[MSG_BUF_SIZE]; 
} gmn_t;

gmn_t* gmn_init(int val);
int gmn_check(gmn_t *pg);

#endif
