(define (windchill W F)
  (let ((sqrt-w (sqrt W)))
    (+ 1.05 (* 0.93 F) (- (* 3.65 W)) (* 3.62 sqrt-w) (* 0.103 F sqrt-w) (* 0.0439 (expt W 2)))))
(define (pressure h)
    (let ((p0 101325)
        (L 0.0065)
        (T0 288.15)
        (g 9.80665)
        (M 0.0289644)
        (R 8.31447))
    (let ((base (- 1 (/ (* L h) T0)))
          (exp (/ (* g M) (* R L))))
      (* p0 (expt base exp))))
)
(define (repeated f n)
  (define (compose f g)
    (lambda (x) (f (g x))))
  (if (= n 1) f
      (compose f (repeated f (- n 1)))))
;(define (repeated f n)
  ;(define (repeated-recursive f x n)
    ;(if (= n 1) (f x)
        ;(f (repeated-recursive f x (- n 1)))))
  ;(lambda (x) (repeated-recursive f x n)))
(define (square x) (* x x))
((repeated square 2) 5)